export const articleTypes = {
  FETCH_ARTICLES_START: 'FETCH_ARTICLES_START',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_FAILURE: 'FETCH_ARTICLES_FAILURE',

  ADD_ARTICLE_START: 'ADD_ARTICLE_START',
  ADD_ARTICLE_SUCCESS: 'ADD_ARTICLE_SUCCESS',
  ADD_ARTICLE_FAILURE: 'ADD_ARTICLE_FAILURE',

  REMOVE_ARTICLE_START: 'REMOVE_ARTICLE_START',
  REMOVE_ARTICLE_SUCCESS: 'REMOVE_ARTICLE_SUCCESS',
  REMOVE_ARTICLE_FAILURE: 'REMOVE_ARTICLE_FAILURE',

  ADD_COMMENT_TO_ARTICLE_START: 'ADD_COMMENT_TO_ARTICLE_START',
  ADD_COMMENT_TO_ARTICLE_SUCCESS: 'ADD_COMMENT_TO_ARTICLE_SUCCESS',
  ADD_COMMENT_TO_ARTICLE_FAILURE: 'ADD_COMMENT_TO_ARTICLE_FAILURE',
};