// export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
// export const HIDE_MOBILE_MENU = "HIDE_MOBILE_MENU";
//
// export const TOGGLE_USER_MENU = "TOGGLE_USER_MENU";
// export const HIDE_USER_MENU = "HIDE_USER_MENU";
//
// export const HIDE_ALL_MENUS = "HIDE_ALL_MENUS";

export const menuTypes = {
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  HIDE_MOBILE_MENU: 'HIDE_MOBILE_MENU',

  TOGGLE_USER_MENU: 'TOGGLE_USER_MENU',
  HIDE_USER_MENU: 'HIDE_USER_MENU',

  HIDE_ALL_MENUS: 'HIDE_ALL_MENUS',
};